name: chat_journal
description: A journal of notes

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  image_picker: ^0.8.4+9
  shared_preferences: ^2.0.13
  flutter_lints: ^1.0.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  sqflite: ^2.0.2
  path: ^1.8.0
  firebase_auth: ^3.3.12
  firebase_core: ^1.13.1
  firebase_database: ^9.0.8
  firebase_storage: ^10.2.10
  local_auth: ^2.0.0
  get_it: ^7.2.0
  share_plus: ^4.0.4
  page_transition: ^2.0.0
  animations: ^2.0.2
  rive: ^0.8.4
  lottie: ^1.3.0
  syncfusion_flutter_charts: ^19.4.41
  firebase_database_mocks: ^0.3.2
  firebase_storage_mocks: ^0.5.0
  firebase_auth_mocks: ^0.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^9.0.3



flutter:
  uses-material-design: true
  assets:
    - assets/images/

